name: Lint all Dockerfiles
on: pull_request
jobs:
  dockerfilelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0
      - run: npm install -g dockerfilelint
      - run: dockerfilelint */Dockerfile
